= ПАВЕЛ ФРОЛОВ
:created-date: 18.06.2023
:publication-date: 22.10.2023
:description: Задача текста — описать причины, влияющие на счастье, и обсудить практические подходы, приводящие к его увеличению.

[#cornerstone_of_text]
== ПАВЕЛ ФРОЛОВ

Серийный Предприниматель 
2 действующих бизнеса
более 20 лет опыта продвижения свободного программного и аппаратного обеспечения в России
В 2000 создал проект ГНУ/Линуксцентр, в 2005-2018 издавал журнал LINUX FORMAT.
В 2012 основал компанию «РОББО» и франшизу детских кружков робототехники «РОББО Клуб»
Cтарший преподаватель в Университетах ИТМО и РГПУ им Герцена
Эксперт Агентства Стратегических Инициатив (АСИ), Фонда Содействия Инновациям (ФСИ), Российского Фонда Развития Информационных Технологий (РФРИТ)
Резидент бизнес-клубов Equium
Глава Российского отделения EO и президент премии GSEA Russia
Соучредитель инвестиционного клуба Капитал и x10 Club Санкт-Петербург
Pre-master x10 Academy
Ученик миллиардера Игоря Рыбакова

Социальные сети:
ВКонтакте: https://vk.com/binocle
Facebook: https://ru-ru.facebook.com/PavelAndreevichFrolov 
Instagram: https://www.instagram.com/pavel.frolov.robbo/
LinkedIn: https://www.linkedin.com/in/pfrolov

 Образование
СПБГПУ, защита информации
MIT + ИТМО, коммерциализация инноваций
Президентская Программа, стратегическое управление финансами

 Ключевые компетенции:
Целеполагание, 
Франчайзинг, 
Коммерциализация инноваций, 
Гранты и госзакупки
Международное масштабирование,
Управление личными финансами
Управление проектами
Построение команды
Программное и аппаратное обеспечение

Ниши:
ИТ
Образование
Электронная коммерция
Интернет-маркетинг и реклама
Open Source
Информационная безопасность

Достижения:
В 44 странах обучаю 100.000+ детей, продал 150+ франшиз РОББО Клуб и 570+ школьных РОББО Классов
Открыл офис ROBBO Finland по приглашению финского правительства 
Открыл офис ROBBO Japan по приглашению японского правительства
Открыл офис ROBBO China по приглашению китайского правительства

Цели и миссия:
Внести вклад в развитие предпринимательства в России
Создать образовательную сеть и обучать 10+ миллионов детей по всему миру


include::../partials/time.adoc[]